'use client';

import { useState, type ReactNode } from 'react';
import Link from 'next/link';
import {
  ArrowRight, Banknote, Bell, Bot, BriefcaseBusiness, Check, CheckCircle2, ChevronRight,
  CircleDollarSign, Clock3, FileCheck2, FileSearch, FileText, Globe2, Headphones, Home, Landmark,
  LogOut, MapPin, MessageCircle, Moon, PackageCheck, Paperclip, Plane, Search, Send, ShieldCheck,
  Ship, Sun, TrendingUp, Upload, UserPlus, Users, Warehouse,
} from 'lucide-react';
import { useTheme } from '@/lib/theme-provider';

type Section = 'dashboard' | 'matching' | 'pool' | 'export';
type IconType = typeof Home;

const navItems: { id: Section; label: string; icon: IconType }[] = [
  { id: 'dashboard', label: 'Dashboard', icon: Home },
  { id: 'matching', label: 'Matching', icon: Users },
  { id: 'pool', label: 'Export Pool', icon: Globe2 },
  { id: 'export', label: 'Export Now', icon: Ship },
];

const summary = [
  ['Active export cases', '2', '1 needs action', BriefcaseBusiness],
  ['Buyer matches', '6', '2 new this week', Users],
  ['Documents in review', '3', '1 revision needed', FileSearch],
  ['Estimated revenue', '$74.8K', 'Across active cases', CircleDollarSign],
] as const;

const transactions = [
  ['Rattan Craft to Netherlands', 'Nordic Living BV', 'Netherlands', 'USD 32,400', 'Settled', '12 May 2026'],
  ['Coffee Beans to Switzerland', 'Alpine Roasters AG', 'Switzerland', 'USD 24,800', 'Settled', '28 Apr 2026'],
  ['Spices to UAE', 'Emirates Pantry LLC', 'UAE', 'USD 18,600', 'Partner review', '17 Apr 2026'],
];

const matches = [
  { id: 'm1', initials: 'HK', name: 'Hana Kobayashi', company: 'Tokyo Natural Foods', role: 'Importer', place: 'Tokyo, Japan', commodity: 'Organic coconut sugar', detail: 'Seeking 8 tons quarterly with food safety evidence.', score: 96, trust: 'Verified buyer' },
  { id: 'm2', initials: 'LM', name: 'Lukas Meier', company: 'Alpine Roasters AG', role: 'Importer', place: 'Zurich, Switzerland', commodity: 'Specialty arabica coffee', detail: 'Looking for traceable micro-lot coffee above 84 points.', score: 92, trust: 'High trust' },
  { id: 'm3', initials: 'SA', name: 'Sara Al Mansoori', company: 'Emirates Pantry LLC', role: 'Importer', place: 'Dubai, UAE', commodity: 'Nutmeg and cloves', detail: 'Requires consistent supply and verified origin documents.', score: 89, trust: 'KYB reviewed' },
  { id: 'm4', initials: 'BP', name: 'Bima Pratama', company: 'Sulawesi Cocoa Collective', role: 'Exporter', place: 'Makassar, Indonesia', commodity: 'Fermented cocoa beans', detail: 'Open to consolidating supply for European demand.', score: 84, trust: 'Community verified' },
];

const communities = [
  { id: 'aceh', name: 'Komunitas Kopi Aceh', region: 'Aceh / Northern Sumatra', commodity: 'Gayo arabica', members: 128, partners: 18, island: 'sumatra', markerX: 116, markerY: 72, color: '#22d3ee' },
  { id: 'demak', name: 'Komunitas Kopi Demak', region: 'Demak / Central Java', commodity: 'Robusta coffee', members: 74, partners: 11, island: 'java', markerX: 300, markerY: 246, color: '#3b82f6' },
  { id: 'sulawesi', name: 'Komunitas Kakao Sulawesi', region: 'Sulawesi', commodity: 'Fermented cocoa', members: 96, partners: 15, island: 'sulawesi', markerX: 520, markerY: 142, color: '#10b981' },
  { id: 'maluku', name: 'Komunitas Rempah Maluku', region: 'Maluku', commodity: 'Nutmeg and cloves', members: 61, partners: 9, island: 'maluku', markerX: 628, markerY: 174, color: '#f59e0b' },
  { id: 'papua', name: 'Komunitas Vanili Papua', region: 'Papua', commodity: 'Premium vanilla', members: 48, partners: 7, island: 'papua', markerX: 733, markerY: 162, color: '#8b5cf6' },
];

const opportunities = [
  { id: 'swiss', initials: 'LM', buyer: 'Alpine Roasters AG', country: 'Switzerland', pickup: 'Takengon, Aceh', category: 'Coffee', goods: 'Specialty Gayo Arabica, 84+ score', volume: '12 tons', value: 'USD 48,000', progress: 68 },
  { id: 'malaysia', initials: 'AN', buyer: 'Nusa Retail Berhad', country: 'Malaysia', pickup: 'Kulon Progo, Yogyakarta', category: 'Food ingredients', goods: 'Organic coconut sugar', volume: '8 tons', value: 'USD 21,600', progress: 42 },
  { id: 'uae', initials: 'SA', buyer: 'Emirates Pantry LLC', country: 'UAE', pickup: 'Ambon, Maluku', category: 'Spices', goods: 'Premium nutmeg and cloves', volume: '5 tons', value: 'USD 34,500', progress: 76 },
  { id: 'japan', initials: 'HK', buyer: 'Tokyo Craft House', country: 'Japan', pickup: 'Cirebon, West Java', category: 'Craft', goods: 'Handmade rattan collection', volume: '1,200 units', value: 'USD 29,400', progress: 55 },
];

const exportSteps = ['Dealing', 'Document', 'Verification', 'Review', 'Escrow Readiness', 'Proof', 'Shipment', 'Settlement'];
const docs = [
  ['Commercial Invoice', 'Reviewed'], ['Packing List', 'Needs revision'],
  ['Certificate of Origin', 'Uploaded'], ['Bill of Lading', 'Approved'], ['HS Code', 'Needs confirmation'],
];

const stageGuidance = [
  { title: 'Open and prepare the shared deal room', happening: 'You opened a deal with Tokyo Natural Foods Co.', todo: 'Invite logistics, settlement partner, and verifier before document exchange.', ai: 'All key parties should be added before document sharing begins.', cta: 'Invite required parties' },
  { title: 'Share export documents with trusted parties', happening: 'The buyer and verifier can review your uploaded export evidence.', todo: 'Confirm the HS Code and align the Packing List weight format.', ai: 'HS Code needs confirmation. Packing List quantity should match the invoice.', cta: 'Review documents' },
  { title: 'Check buyer, exporter, and document consistency', happening: 'NEXIIport is organizing verification signals into one checklist.', todo: 'Review the remaining commodity requirement check.', ai: 'Buyer and exporter profiles are verified. Commodity requirement needs one final check.', cta: 'Run verification check' },
  { title: 'Review the trade assurance summary', happening: 'Your case is being summarized before partner review.', todo: 'Review document risk, buyer trust, and logistics readiness.', ai: 'Document risk is low after the HS Code is confirmed.', cta: 'Open assurance summary' },
  { title: 'Prepare funds readiness for partner review', happening: 'Payment protection and funds readiness signals are being organized.', todo: 'Review the partner status and the remaining risk note.', ai: 'Escrow readiness is 82%. This case is not yet a payment instruction.', cta: 'Check readiness signals' },
  { title: 'Collect evidence at every export checkpoint', happening: 'Packing and inspection evidence are ready for partner review.', todo: 'Add dispatch proof before the shipment leaves origin.', ai: 'The next required proof is dispatch confirmation.', cta: 'Check shipment proof' },
  { title: 'Follow the goods from warehouse to buyer', happening: 'Your goods are currently moving toward the destination port.', todo: 'Monitor the route and prepare destination arrival proof.', ai: 'Goods are currently in transit. Next proof needed: destination port arrival confirmation.', cta: 'Advance shipment checkpoint' },
  { title: 'Review the final settlement readiness summary', happening: 'Verified evidence supports a partner-ready recommendation.', todo: 'Share the trade assurance summary with the settlement partner.', ai: 'Case is ready for partner review based on verified documents and shipment evidence.', cta: 'View settlement readiness' },
];

function Card({ children, className = '' }: { children: ReactNode; className?: string }) {
  return <section className={`rounded-2xl border border-slate-200/75 bg-white/90 shadow-sm dark:border-white/10 dark:bg-white/[0.035] ${className}`}>{children}</section>;
}

function Badge({ children, tone = 'blue' }: { children: ReactNode; tone?: 'blue' | 'green' | 'amber' | 'slate' }) {
  const tones = { blue: 'bg-blue-500/10 text-blue-600 dark:text-cyan-300', green: 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-300', amber: 'bg-amber-500/10 text-amber-700 dark:text-amber-300', slate: 'bg-slate-500/10 text-slate-600 dark:text-slate-300' };
  return <span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-bold ${tones[tone]}`}>{children}</span>;
}

function Heading({ eyebrow, title, copy, action }: { eyebrow: string; title: string; copy: string; action?: ReactNode }) {
  return <div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-blue-600 dark:text-cyan-400">{eyebrow}</p><h1 className="mt-2 font-heading text-2xl font-extrabold tracking-tight sm:text-3xl">{title}</h1><p className="mt-2 max-w-2xl text-xs leading-relaxed text-slate-500 dark:text-slate-400 sm:text-sm">{copy}</p></div>{action}</div>;
}

function NexiiWordmark() {
  return <div className="min-w-0">
    <div className="flex items-end gap-[5px] whitespace-nowrap leading-none">
      <span className="bg-gradient-to-r from-blue-700 to-sky-500 bg-clip-text font-heading text-[25px] font-black text-transparent dark:from-blue-400 dark:to-cyan-300 dark:drop-shadow-[0_0_7px_rgba(34,211,238,0.28)]">NEX</span>
      <svg viewBox="0 0 72 72" className="mb-[1px] h-[28px] w-[28px] shrink-0 overflow-visible dark:drop-shadow-[0_0_6px_rgba(34,211,238,0.3)]" aria-hidden="true">
        <defs>
          <linearGradient id="wordmark-pillar-left" x1="0" y1="0" x2="1" y2="1">
            <stop offset="0" stopColor="#22d3ee" />
            <stop offset="1" stopColor="#2563eb" />
          </linearGradient>
          <linearGradient id="wordmark-pillar-right" x1="0" y1="0" x2="1" y2="1">
            <stop offset="0" stopColor="#06b6d4" />
            <stop offset="1" stopColor="#0284c7" />
          </linearGradient>
        </defs>
        <path d="M4 2h24v22c0 20-2 34-8 46H0c12-13 16-28 16-49V2Z" fill="url(#wordmark-pillar-left)" />
        <path d="M44 2h24v19c0 21 4 36 16 49H64c-6-12-8-26-8-46V2H44Z" fill="url(#wordmark-pillar-right)" />
        <path d="m36 48 10 22H26Z" fill="#fbbf24" />
      </svg>
      <span className="bg-gradient-to-r from-sky-500 to-cyan-400 bg-clip-text font-heading text-[24px] font-medium text-transparent dark:from-cyan-300 dark:to-sky-400 dark:drop-shadow-[0_0_7px_rgba(34,211,238,0.25)]">port</span>
    </div>
    <span className="mt-1.5 block truncate text-[6px] font-bold uppercase tracking-[0.14em] text-slate-500 dark:text-slate-400">AI-powered trade trust infrastructure</span>
  </div>;
}

export default function ExporterAppPage() {
  const { theme, toggleTheme, mounted } = useTheme();
  const [section, setSection] = useState<Section>('dashboard');
  const [community, setCommunity] = useState('aceh');
  const [connected, setConnected] = useState<string[]>([]);
  const [selectedOpportunity, setSelectedOpportunity] = useState('malaysia');
  const [exportStep, setExportStep] = useState(0);

  const navigate = (next: Section) => { setSection(next); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const selectedCommunity = communities.find((item) => item.id === community) ?? communities[0];
  const selectedPool = opportunities.find((item) => item.id === selectedOpportunity) ?? opportunities[0];

  return (
    <div className="min-h-screen overflow-x-hidden bg-slate-100 text-slate-950 transition-colors dark:bg-[#030712] dark:text-white">
      <aside className="fixed inset-y-0 left-0 z-30 hidden w-64 border-r border-slate-200/70 bg-white/95 p-4 backdrop-blur-xl dark:border-white/10 dark:bg-[#060c17]/95 lg:flex lg:flex-col">
        <Link href="/" aria-label="NEXIIport home" className="block rounded-xl px-2 py-2 transition hover:bg-blue-500/[0.05] dark:hover:bg-cyan-400/[0.04]"><NexiiWordmark /></Link>
        <nav className="mt-7 space-y-1">{navItems.map((item) => { const Icon = item.icon; return <button key={item.id} onClick={() => navigate(item.id)} className={`flex min-h-11 w-full items-center gap-3 rounded-xl px-3 text-left text-xs font-bold transition ${section === item.id ? 'bg-blue-600 text-white shadow-lg shadow-blue-500/20' : 'text-slate-500 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-white/[0.06]'}`}><Icon className="h-4 w-4" />{item.label}</button>; })}</nav>
        <Card className="mt-auto p-4"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-blue-600 to-cyan-500 text-xs font-black text-white">AE</span><div className="min-w-0"><b className="block truncate text-xs">Aruna Export</b><span className="text-[10px] text-slate-400">Verified exporter</span></div></div><Link href="/login" className="mt-4 flex items-center gap-2 text-[10px] font-bold text-slate-400 hover:text-rose-500"><LogOut className="h-3.5 w-3.5" />Exit demo</Link></Card>
      </aside>

      <div className="lg:pl-64">
        <header className="sticky top-0 z-20 border-b border-slate-200/70 bg-white/90 backdrop-blur-xl dark:border-white/10 dark:bg-[#030712]/90">
          <div className="flex h-16 items-center justify-between px-4 sm:px-6 lg:px-8"><div><p className="text-[9px] font-bold uppercase tracking-wider text-blue-600 dark:text-cyan-400">Aruna Export Indonesia</p><b className="text-xs sm:text-sm">{navItems.find((item) => item.id === section)?.label}</b></div><div className="flex items-center gap-1"><button className="hidden min-h-10 items-center gap-2 rounded-xl border border-slate-200 px-3 text-xs text-slate-400 dark:border-white/10 sm:flex"><Search className="h-3.5 w-3.5" />Search workspace</button><button onClick={toggleTheme} className="flex h-10 w-10 items-center justify-center rounded-xl text-slate-500 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-white/10" aria-label="Toggle theme">{mounted ? theme === 'dark' ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" /> : null}</button><button className="relative flex h-10 w-10 items-center justify-center rounded-xl text-slate-500 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-white/10" aria-label="Notifications"><Bell className="h-4 w-4" /><span className="absolute right-2.5 top-2.5 h-1.5 w-1.5 rounded-full bg-cyan-400" /></button></div></div>
          <nav className="flex gap-1 overflow-x-auto px-4 pb-3 lg:hidden">{navItems.map((item) => { const Icon = item.icon; return <button key={item.id} onClick={() => navigate(item.id)} className={`flex min-h-10 shrink-0 items-center gap-2 rounded-xl px-3 text-[10px] font-bold ${section === item.id ? 'bg-blue-600 text-white' : 'bg-slate-100 text-slate-500 dark:bg-white/[0.05] dark:text-slate-300'}`}><Icon className="h-3.5 w-3.5" />{item.label}</button>; })}</nav>
        </header>

        <main className="mx-auto max-w-[1500px] px-4 py-6 pb-24 sm:px-6 lg:px-8 lg:pb-10">
          {section === 'dashboard' && <Dashboard navigate={navigate} />}
          {section === 'matching' && <Matching community={community} setCommunity={setCommunity} connected={connected} setConnected={setConnected} selectedCommunity={selectedCommunity} />}
          {section === 'pool' && <ExportPool selected={selectedOpportunity} setSelected={setSelectedOpportunity} selectedPool={selectedPool} navigate={navigate} />}
          {section === 'export' && <ExportNow step={exportStep} setStep={setExportStep} opportunity={selectedPool} />}
        </main>
      </div>

      <nav className="fixed bottom-0 left-0 right-0 z-30 grid h-[70px] grid-cols-4 border-t border-slate-200/70 bg-white/95 px-1 backdrop-blur-xl dark:border-white/10 dark:bg-[#06101c]/95 lg:hidden">{navItems.map((item) => { const Icon = item.icon; return <button key={item.id} onClick={() => navigate(item.id)} className={`flex flex-col items-center justify-center gap-1 text-[9px] font-bold ${section === item.id ? 'text-blue-600 dark:text-cyan-300' : 'text-slate-400'}`}><Icon className="h-5 w-5" />{item.label}</button>; })}</nav>
    </div>
  );
}

function Dashboard({ navigate }: { navigate: (section: Section) => void }) {
  return <><Heading eyebrow="Exporter command center" title="Welcome back, Aruna Export" copy="Manage your buyers, active cases, documents, and export readiness from one connected workspace." action={<Badge tone="green">Verified exporter</Badge>} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{summary.map(([label, value, detail, Icon]) => <button key={label} className="rounded-2xl border border-slate-200/75 bg-white p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-blue-500/25 dark:border-white/10 dark:bg-white/[0.035]"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-500/10 text-blue-600 dark:text-cyan-300"><Icon className="h-4 w-4" /></span><span className="mt-4 block text-[9px] font-bold uppercase tracking-wider text-slate-400">{label}</span><b className="mt-1 block font-heading text-xl">{value}</b><span className="mt-1 block text-[10px] text-slate-400">{detail}</span></button>)}</div>
    <Card className="mt-6 p-5 sm:p-6"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><Badge>Active export case</Badge><h2 className="mt-3 font-heading text-xl font-extrabold">Coconut Sugar Export to Japan</h2><p className="mt-1 text-xs text-slate-400">Tokyo Natural Foods Co. | Document stage | USD 18,600</p></div><PackageCheck className="h-6 w-6 text-blue-600 dark:text-cyan-300" /></div><div className="mt-6 h-2 rounded-full bg-slate-100 dark:bg-white/10"><div className="h-full w-[62%] rounded-full bg-gradient-to-r from-blue-600 to-cyan-400" /></div><div className="mt-5 rounded-xl bg-amber-500/[0.08] p-4 text-xs"><b>Next action:</b> Confirm HS code before buyer submission.</div><button onClick={() => navigate('export')} className="mt-5 flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-slate-950 text-xs font-bold text-white dark:bg-cyan-300 dark:text-slate-950">Continue Export Now <ArrowRight className="h-4 w-4" /></button></Card>
    <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Open Matching','matching',Users],['View Export Pool','pool',Globe2],['Continue Export Now','export',Ship],['Review Documents','export',FileSearch]].map(([label,id,Icon]) => <button key={label as string} onClick={() => navigate(id as Section)} className="flex min-h-14 items-center gap-3 rounded-xl border border-slate-200 bg-white p-3 text-left text-xs font-bold shadow-sm hover:border-blue-500/30 dark:border-white/10 dark:bg-white/[0.035]"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-500/10 text-blue-600 dark:text-cyan-300"><Icon className="h-4 w-4" /></span><span className="flex-1">{label as string}</span><ChevronRight className="h-4 w-4 text-slate-300" /></button>)}</div>
    <Card className="mt-6 overflow-hidden"><div className="border-b border-slate-200/70 p-5 dark:border-white/10"><h2 className="font-heading text-lg font-extrabold">Historical transactions</h2><p className="mt-1 text-xs text-slate-400">Your completed and reviewed export history.</p></div><div className="divide-y divide-slate-200/70 dark:divide-white/10">{transactions.map((row) => <div key={row[0]} className="grid gap-2 p-4 text-xs sm:grid-cols-[1.4fr_1fr_0.8fr_0.7fr_0.7fr] sm:items-center"><div><b>{row[0]}</b><p className="mt-1 text-[10px] text-slate-400">{row[1]}</p></div><span>{row[2]}</span><b>{row[3]}</b><Badge tone={row[4] === 'Settled' ? 'green' : 'amber'}>{row[4]}</Badge><span className="text-slate-400">{row[5]}</span></div>)}</div></Card></>;
}

function Matching({ community, setCommunity, connected, setConnected, selectedCommunity }: { community: string; setCommunity: (id: string) => void; connected: string[]; setConnected: (ids: string[]) => void; selectedCommunity: typeof communities[number] }) {
  return <><Heading eyebrow="Partner discovery" title="Matching" copy="Explore verified trading partners and Indonesian commodity communities aligned with your export goals." action={<Badge>{connected.length} connections</Badge>} />
    <div className="flex snap-x gap-4 overflow-x-auto pb-3">{matches.map((match) => <Card key={match.id} className="min-w-[280px] snap-start p-5 sm:min-w-[330px]"><div className="flex items-start justify-between"><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-blue-600 to-cyan-400 font-heading text-lg font-black text-white">{match.initials}</span><b className="font-heading text-2xl text-blue-600 dark:text-cyan-300">{match.score}%</b></div><Badge tone="green">{match.trust}</Badge><h2 className="mt-4 font-heading text-lg font-extrabold">{match.name}</h2><p className="text-xs text-slate-400">{match.company} | {match.role}</p><p className="mt-3 flex items-center gap-1 text-[10px] font-bold text-slate-400"><MapPin className="h-3.5 w-3.5" />{match.place}</p><div className="mt-4 rounded-xl bg-slate-50 p-3 dark:bg-white/[0.04]"><b className="text-xs">{match.commodity}</b><p className="mt-1 text-[10px] leading-relaxed text-slate-400">{match.detail}</p></div><div className="mt-4 grid grid-cols-2 gap-2"><button className="min-h-10 rounded-xl border border-slate-200 text-xs font-bold dark:border-white/10">View profile</button><button onClick={() => setConnected(connected.includes(match.id) ? connected.filter((id) => id !== match.id) : [...connected, match.id])} className={`min-h-10 rounded-xl text-xs font-bold ${connected.includes(match.id) ? 'bg-emerald-500 text-white' : 'bg-blue-600 text-white'}`}>{connected.includes(match.id) ? 'Connected' : 'Connect'}</button></div></Card>)}</div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[0.72fr_1.28fr]"><Card className="p-5 sm:p-6"><h2 className="font-heading text-lg font-extrabold">Search Indonesian commodity communities</h2><p className="mt-1 text-xs text-slate-400">Select a region to reveal its commodity network and active export partners.</p><div className="mt-5 space-y-2">{communities.map((item) => <button key={item.id} onClick={() => setCommunity(item.id)} className={`flex min-h-14 w-full items-center gap-3 rounded-xl border p-3 text-left transition ${community === item.id ? 'border-blue-500/40 bg-blue-500/[0.08] shadow-sm shadow-blue-500/10' : 'border-slate-200 hover:border-blue-500/20 dark:border-white/10'}`}><span className="flex h-9 w-9 items-center justify-center rounded-xl text-white" style={{ backgroundColor: item.color }}><MapPin className="h-4 w-4" /></span><span className="min-w-0 flex-1"><b className="block truncate text-xs">{item.name}</b><span className="text-[10px] text-slate-400">{item.region} | {item.commodity}</span></span><ChevronRight className="h-4 w-4 text-slate-300" /></button>)}</div></Card>
      <IndonesiaCommunityMap selected={community} setSelected={setCommunity} community={selectedCommunity} /></div></>;
}

function IndonesiaCommunityMap({ selected, setSelected, community }: { selected: string; setSelected: (id: string) => void; community: typeof communities[number] }) {
  const islandFill = (island: string) => community.island === island ? community.color : 'rgba(59,130,246,0.18)';
  const islandStroke = (island: string) => community.island === island ? community.color : 'rgba(34,211,238,0.28)';
  return <Card className="overflow-hidden">
    <div className="border-b border-slate-200/70 p-5 dark:border-white/10 sm:p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><Badge>Indonesia community map</Badge><h2 className="mt-3 font-heading text-xl font-extrabold">{community.region}</h2><p className="mt-1 text-xs text-slate-400">{community.name} is highlighted on the archipelago.</p></div><span className="flex h-11 w-11 items-center justify-center rounded-xl text-white shadow-lg" style={{ backgroundColor: community.color }}><MapPin className="h-5 w-5" /></span></div></div>
    <div className="relative bg-slate-950 p-3 sm:p-5"><div className="absolute inset-0 grid-pattern opacity-20" />
      <svg viewBox="0 0 820 330" className="relative z-10 h-auto w-full" role="img" aria-label="Stylized map of Indonesia with commodity community locations">
        <defs><filter id="islandGlow"><feGaussianBlur stdDeviation="5" result="blur" /><feMerge><feMergeNode in="blur" /><feMergeNode in="SourceGraphic" /></feMerge></filter></defs>
        <path d="M65 62 C88 45 116 48 135 69 L205 174 C215 190 205 210 187 204 L153 178 L125 142 L96 113 L70 91 C60 82 57 70 65 62Z" fill={islandFill('sumatra')} stroke={islandStroke('sumatra')} strokeWidth="3" filter={community.island === 'sumatra' ? 'url(#islandGlow)' : undefined} />
        <path d="M208 228 C255 218 337 220 410 229 C421 231 424 242 413 247 C350 257 270 256 214 246 C202 244 198 233 208 228Z" fill={islandFill('java')} stroke={islandStroke('java')} strokeWidth="3" filter={community.island === 'java' ? 'url(#islandGlow)' : undefined} />
        <path d="M424 247 l18 5 l8 12 l-17 5 l-16 -9Z M457 257 l16 3 l9 10 l-13 7 l-18 -8Z M488 265 l17 3 l11 9 l-12 8 l-19 -8Z" fill={islandFill('nusa')} stroke={islandStroke('nusa')} strokeWidth="2" />
        <path d="M290 75 C327 56 389 58 421 87 L420 155 C408 181 374 202 330 190 L297 160 L278 115Z" fill={islandFill('kalimantan')} stroke={islandStroke('kalimantan')} strokeWidth="3" />
        <path d="M500 87 C518 72 542 80 547 100 L538 128 L562 116 L579 126 L558 143 L570 177 L553 196 L536 166 L515 183 L497 173 L515 143 L493 121Z" fill={islandFill('sulawesi')} stroke={islandStroke('sulawesi')} strokeWidth="3" filter={community.island === 'sulawesi' ? 'url(#islandGlow)' : undefined} />
        <path d="M614 130 l13 -8 l9 10 l-8 12 l-14 -4Z M640 154 l15 -8 l11 10 l-8 13 l-16 -2Z M617 181 l11 -8 l10 9 l-7 13 l-13 -2Z M668 188 l13 -5 l9 10 l-8 10 l-13 -3Z" fill={islandFill('maluku')} stroke={islandStroke('maluku')} strokeWidth="2.5" filter={community.island === 'maluku' ? 'url(#islandGlow)' : undefined} />
        <path d="M706 109 C741 96 789 107 806 132 L800 191 C775 208 738 205 710 188 L694 153Z" fill={islandFill('papua')} stroke={islandStroke('papua')} strokeWidth="3" filter={community.island === 'papua' ? 'url(#islandGlow)' : undefined} />
        <text x="100" y="212" fill="#64748b" fontSize="11">SUMATRA</text><text x="300" y="275" fill="#64748b" fontSize="11">JAVA</text><text x="315" y="125" fill="#64748b" fontSize="11">KALIMANTAN</text><text x="500" y="215" fill="#64748b" fontSize="11">SULAWESI</text><text x="615" y="220" fill="#64748b" fontSize="11">MALUKU</text><text x="742" y="225" fill="#64748b" fontSize="11">PAPUA</text>
        {communities.map((item) => <g key={item.id} onClick={() => setSelected(item.id)} className="cursor-pointer"><circle cx={item.markerX} cy={item.markerY} r={selected === item.id ? 15 : 10} fill={item.color} opacity={selected === item.id ? 0.25 : 0.12} /><circle cx={item.markerX} cy={item.markerY} r={selected === item.id ? 7 : 5} fill={item.color} stroke="#ffffff" strokeWidth="2" /><text x={item.markerX + 10} y={item.markerY - 10} fill={selected === item.id ? '#ffffff' : '#94a3b8'} fontSize="10" fontWeight="700">{item.id.toUpperCase()}</text></g>)}
      </svg>
    </div>
    <div className="grid gap-3 p-5 sm:grid-cols-3 sm:p-6"><div className="rounded-xl bg-slate-50 p-3 dark:bg-white/[0.04]"><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Commodity</p><b className="mt-1 block text-xs">{community.commodity}</b></div><div className="rounded-xl bg-slate-50 p-3 dark:bg-white/[0.04]"><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Members</p><b className="mt-1 block text-xs">{community.members} verified</b></div><div className="rounded-xl bg-slate-50 p-3 dark:bg-white/[0.04]"><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Export partners</p><b className="mt-1 block text-xs">{community.partners} available</b></div><button className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-blue-600 to-cyan-500 text-xs font-bold text-white sm:col-span-3">Explore community <ArrowRight className="h-4 w-4" /></button></div>
  </Card>;
}

function ExportPool({ selected, setSelected, selectedPool, navigate }: { selected: string; setSelected: (id: string) => void; selectedPool: typeof opportunities[number]; navigate: (section: Section) => void }) {
  return <><Heading eyebrow="Open buyer demand" title="Export Pool" copy="Browse current buyer needs, select an opportunity, and turn demand into an active export case." action={<Badge tone="green">{opportunities.length} open opportunities</Badge>} />
    <div className="grid gap-4 md:grid-cols-2 2xl:grid-cols-4">{opportunities.map((item) => <button key={item.id} onClick={() => setSelected(item.id)} className={`overflow-hidden rounded-2xl border bg-white p-5 text-left shadow-sm transition hover:-translate-y-1 dark:bg-white/[0.035] ${selected === item.id ? 'border-blue-500 ring-4 ring-blue-500/10' : 'border-slate-200/75 dark:border-white/10'}`}><div className="flex items-start justify-between"><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-blue-600 to-cyan-400 font-heading font-black text-white">{item.initials}</span><Badge>{item.country}</Badge></div><p className="mt-5 text-[9px] font-bold uppercase tracking-wider text-slate-400">{item.category}</p><h2 className="mt-1 font-heading text-lg font-extrabold">{item.goods}</h2><p className="mt-2 text-xs text-slate-400">{item.buyer}</p><p className="mt-4 flex items-center gap-1 text-[10px] text-slate-400"><MapPin className="h-3.5 w-3.5" />Pickup: {item.pickup}</p><div className="mt-4 h-1.5 rounded-full bg-slate-100 dark:bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-blue-600 to-cyan-400" style={{ width: `${item.progress}%` }} /></div><div className="mt-3 flex justify-between text-[10px]"><span>{item.volume}</span><b>{item.value}</b></div></button>)}</div>
    <Card className="mt-6 p-5 sm:p-6"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><Badge tone="green">Selected opportunity</Badge><h2 className="mt-3 font-heading text-xl font-extrabold">{selectedPool.goods} for {selectedPool.buyer}</h2><p className="mt-1 text-xs text-slate-400">{selectedPool.country} | {selectedPool.volume} | {selectedPool.value}</p></div><button onClick={() => navigate('export')} className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-blue-600 to-cyan-500 px-5 text-xs font-bold text-white">Start Export Now <ArrowRight className="h-4 w-4" /></button></div></Card></>;
}

function ExportNow({ step, setStep, opportunity }: { step: number; setStep: (step: number) => void; opportunity: typeof opportunities[number] }) {
  const active = exportSteps[step];
  const guide = stageGuidance[step];
  const [completed, setCompleted] = useState<number[]>([]);
  const completeStage = () => setCompleted((items) => items.includes(step) ? items : [...items, step]);
  return <><Heading eyebrow="My guided export journey" title="Export Now" copy={`You are exporting 2 tons of coconut sugar to ${opportunity.buyer}. NEXIIport guides every party, action, and evidence checkpoint.`} action={<Badge tone="amber">{active}</Badge>} />
    <Card className="mb-5 p-4"><div className="flex gap-2 overflow-x-auto pb-1">{exportSteps.map((item, index) => <button key={item} onClick={() => setStep(index)} className={`min-h-11 shrink-0 rounded-xl px-3 text-[10px] font-bold transition ${index === step ? 'bg-blue-600 text-white shadow-lg shadow-blue-500/20' : completed.includes(index) || index < step ? 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-300' : 'bg-slate-100 text-slate-400 dark:bg-white/[0.04]'}`}>{completed.includes(index) && <Check className="mr-1 inline h-3 w-3" />}{item}</button>)}</div></Card>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="min-w-0"><Card className="mb-4 p-5 sm:p-6"><Badge tone={completed.includes(step) ? 'green' : 'blue'}>{completed.includes(step) ? 'Stage action completed' : `Current stage: ${active}`}</Badge><h2 className="mt-3 font-heading text-xl font-extrabold">{guide.title}</h2><div className="mt-5 space-y-4"><div><p className="text-[9px] font-bold uppercase tracking-wider text-blue-600 dark:text-cyan-300">What is happening</p><p className="mt-2 text-sm leading-relaxed text-slate-600 dark:text-slate-300">{guide.happening}</p></div><div className="border-t border-slate-200 pt-4 dark:border-white/10"><p className="text-[9px] font-bold uppercase tracking-wider text-amber-600 dark:text-amber-300">What I need to do</p><p className="mt-2 text-sm leading-relaxed text-slate-600 dark:text-slate-300">{guide.todo}</p></div></div></Card><ExportStage active={active} /><button onClick={completeStage} className={`mt-4 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl text-xs font-bold ${completed.includes(step) ? 'bg-emerald-500 text-white' : 'bg-gradient-to-r from-blue-600 to-cyan-500 text-white shadow-lg shadow-blue-500/20'}`}>{completed.includes(step) ? <CheckCircle2 className="h-4 w-4" /> : <ArrowRight className="h-4 w-4" />}{completed.includes(step) ? 'Stage action completed' : guide.cta}</button></div><div className="space-y-4 xl:sticky xl:top-24 xl:self-start"><ExportAIPanel active={active} guide={guide} step={step} setStep={setStep} /><RevenueCard /><SupportCard /></div></div></>;
}

function ExportStage({ active }: { active: string }) {
  const [invited, setInvited] = useState(false);
  const [documents, setDocuments] = useState<Record<string, string>>({ 'Commercial Invoice': 'Attached', 'Packing List': 'Pending', 'Certificate of Origin': 'Pending', 'HS Code': 'Revised' });
  const [verified, setVerified] = useState(false);
  const [reviewResponded, setReviewResponded] = useState(false);
  const [readinessChecked, setReadinessChecked] = useState(false);
  const [proofs, setProofs] = useState<Record<string, string>>({ 'Packing proof': 'Uploaded', 'Dispatch proof': 'Missing', 'Inspection proof': 'Reviewed', 'Arrival proof': 'Missing' });
  const [shipmentPoint, setShipmentPoint] = useState(3);
  const [settlementChecked, setSettlementChecked] = useState(false);
  const action = 'flex min-h-10 items-center justify-center gap-2 rounded-xl px-3 text-[10px] font-bold transition';

  if (active === 'Dealing') {
    const participants = [['Me / Aruna Export', 'Joined', Send], ['Tokyo Natural Foods', 'Joined', Users], ['Logistics Partner', invited ? 'Joined' : 'Pending', Ship], ['Settlement Partner', 'Pending', Landmark], ['Verifier', 'Joined', ShieldCheck]] as const;
    return <Card className="p-5 sm:p-6"><Badge>Shared deal room</Badge><h2 className="mt-3 font-heading text-xl font-extrabold">Bring every export partner into one room.</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{participants.map(([label,status,Icon]) => <div key={label} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 dark:border-white/10"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-500/10 text-blue-600 dark:text-cyan-300"><Icon className="h-4 w-4" /></span><div className="min-w-0 flex-1"><b className="block truncate text-xs">{label}</b><span className="text-[10px] text-slate-400">{status}</span></div><Badge tone={status === 'Joined' ? 'green' : 'amber'}>{status}</Badge></div>)}</div><button onClick={() => setInvited(true)} className={`${action} mt-5 w-full border border-blue-500/30 text-blue-600 dark:text-cyan-300`}><UserPlus className="h-4 w-4" />{invited ? 'Invitation sent' : 'Invite participant'}</button></Card>;
  }
  if (active === 'Document') {
    const update = (name: string, status: string) => setDocuments((current) => ({ ...current, [name]: status }));
    return <Card className="p-5 sm:p-6"><Badge>Exporter document exchange</Badge><h2 className="mt-3 font-heading text-xl font-extrabold">Attach and share documents with the buyer and verifier.</h2><p className="mt-2 text-xs text-slate-400">You control what leaves the exporter workspace and who receives it.</p><div className="mt-5 space-y-3">{Object.entries(documents).map(([name,status]) => <div key={name} className="flex min-h-14 flex-col gap-3 rounded-xl border border-slate-200 p-3 dark:border-white/10 sm:flex-row sm:items-center"><FileText className="h-4 w-4 shrink-0 text-blue-500" /><div className="min-w-0 flex-1"><b className="block text-xs">{name}</b><span className="text-[10px] text-slate-400">{status === 'Sent' ? 'Shared with buyer and verifier' : 'In exporter workspace'}</span></div><Badge tone={status === 'Pending' || status === 'Revised' ? 'amber' : 'green'}>{status}</Badge><div className="flex gap-2"><button onClick={() => update(name, 'Attached')} className={`${action} bg-slate-100 text-slate-600 dark:bg-white/[0.06] dark:text-slate-200`}><Paperclip className="h-3.5 w-3.5" />Attach</button><button onClick={() => update(name, 'Sent')} disabled={status === 'Pending'} className={`${action} bg-blue-600 text-white disabled:opacity-40`}><Send className="h-3.5 w-3.5" />Send</button></div></div>)}</div></Card>;
  }
  if (active === 'Verification') {
    const checks = [['Exporter profile verified', true], ['Buyer profile verified', true], ['Document consistency check', verified], ['Commodity suitability check', verified]] as const;
    return <Card className="p-5 sm:p-6"><Badge>Case validation</Badge><h2 className="mt-3 font-heading text-xl font-extrabold">Validate trust signals before partner review.</h2><div className="mt-5 space-y-3">{checks.map(([label,passed]) => <div key={label} className="flex min-h-14 items-center gap-3 rounded-xl bg-slate-50 p-3 dark:bg-white/[0.04]"><span className={`flex h-8 w-8 items-center justify-center rounded-full ${passed ? 'bg-emerald-500/15 text-emerald-500' : 'bg-amber-500/15 text-amber-500'}`}>{passed ? <Check className="h-4 w-4" /> : <Clock3 className="h-4 w-4" />}</span><b className="flex-1 text-xs">{label}</b><Badge tone={passed ? 'green' : 'amber'}>{passed ? 'Passed' : 'Pending'}</Badge></div>)}</div><button onClick={() => setVerified(true)} className={`${action} mt-5 w-full bg-gradient-to-r from-blue-600 to-cyan-500 text-white`}><ShieldCheck className="h-4 w-4" />{verified ? 'Case verified' : 'Run verification'}</button></Card>;
  }
  if (active === 'Review') {
    return <Card className="p-5 sm:p-6"><Badge tone="amber">Manual buyer review</Badge><h2 className="mt-3 font-heading text-xl font-extrabold">The buyer is reading your verified export case.</h2><div className="mt-5 rounded-2xl border border-blue-500/20 bg-blue-500/[0.05] p-4"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-600 text-xs font-black text-white">HK</span><div><b className="block text-xs">Hana Kobayashi</b><span className="text-[10px] text-slate-400">Tokyo Natural Foods - Buyer reviewer</span></div></div><p className="mt-4 text-xs leading-relaxed text-slate-600 dark:text-slate-300">&ldquo;Please confirm the final packing quantity before buyer submission.&rdquo;</p></div><div className="mt-4 space-y-2">{[['Packing List reviewed','Accepted'],['Commercial Invoice accepted','Accepted'],['Buyer confirmation',reviewResponded ? 'Response sent' : 'Waiting approval']].map(([label,status]) => <div key={label} className="flex items-center justify-between gap-3 rounded-xl bg-slate-50 p-3 dark:bg-white/[0.04]"><span className="text-xs">{label}</span><Badge tone={status === 'Waiting approval' ? 'amber' : 'green'}>{status}</Badge></div>)}</div><div className="mt-5 grid gap-2 sm:grid-cols-2"><button className={`${action} border border-slate-200 text-slate-600 dark:border-white/10 dark:text-slate-200`}><FileSearch className="h-4 w-4" />View review notes</button><button onClick={() => setReviewResponded(true)} className={`${action} bg-blue-600 text-white`}><MessageCircle className="h-4 w-4" />{reviewResponded ? 'Response sent' : 'Respond to buyer'}</button></div></Card>;
  }
  if (active === 'Escrow Readiness') {
    return <Card className="p-5 sm:p-6"><Badge tone="amber">Partner readiness signals</Badge><h2 className="mt-3 font-heading text-xl font-extrabold">Prepare the case for regulated partner review.</h2><div className="mt-5 rounded-2xl bg-slate-950 p-5 text-white"><div className="flex items-end justify-between"><div><p className="text-[9px] font-bold uppercase tracking-wider text-cyan-300">Readiness score</p><b className="mt-2 block font-heading text-4xl">{readinessChecked ? '91%' : '82%'}</b></div><ShieldCheck className="h-9 w-9 text-cyan-300" /></div><div className="mt-4 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-blue-500 to-cyan-300 transition-all" style={{ width: readinessChecked ? '91%' : '82%' }} /></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><StatusTile title="Partner review" copy={readinessChecked ? 'Ready to share' : 'Pending readiness check'} icon={Landmark} /><StatusTile title="Funds readiness note" copy="Buyer signal confirmed" icon={Banknote} /></div><p className="mt-4 rounded-xl bg-amber-500/[0.08] p-4 text-[11px] leading-relaxed text-slate-300">NEXIIport provides readiness signals only. Financial action remains subject to regulated partner review.</p><button onClick={() => setReadinessChecked(true)} className={`${action} mt-5 w-full bg-blue-600 text-white`}><ShieldCheck className="h-4 w-4" />{readinessChecked ? 'Readiness checked' : 'Check readiness'}</button></Card>;
  }
  if (active === 'Proof') {
    const update = (name: string, status: string) => setProofs((current) => ({ ...current, [name]: status }));
    return <Card className="p-5 sm:p-6"><Badge>Trade evidence room</Badge><h2 className="mt-3 font-heading text-xl font-extrabold">Collect proof from real export checkpoints.</h2><p className="mt-2 text-xs text-slate-400">These files prove physical handling and delivery progress.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{Object.entries(proofs).map(([name,status]) => <div key={name} className="rounded-xl border border-slate-200 p-4 dark:border-white/10"><div className="flex items-start justify-between gap-2"><PackageCheck className="h-5 w-5 text-blue-500" /><Badge tone={status === 'Missing' ? 'amber' : 'green'}>{status}</Badge></div><b className="mt-4 block text-xs">{name}</b><div className="mt-4 flex gap-2"><button onClick={() => update(name, 'Uploaded')} className={`${action} flex-1 bg-slate-100 text-slate-600 dark:bg-white/[0.06] dark:text-slate-200`}><Upload className="h-3.5 w-3.5" />Attach</button><button onClick={() => update(name, 'Reviewed')} disabled={status === 'Missing'} className={`${action} flex-1 bg-blue-600 text-white disabled:opacity-40`}><Send className="h-3.5 w-3.5" />Send</button></div></div>)}</div></Card>;
  }
  if (active === 'Shipment') {
    const milestones = [['Warehouse', Warehouse], ['Picked up', PackageCheck], ['Origin port', Ship], ['In transit', Plane], ['Customs', ShieldCheck], ['Destination', MapPin], ['Delivered', CheckCircle2]] as const;
    return <Card className="p-5 sm:p-6"><Badge tone="green">Live shipment tracker</Badge><h2 className="mt-3 font-heading text-xl font-extrabold">Know where your goods are right now.</h2><div className="mt-5 overflow-hidden rounded-2xl bg-slate-950 p-4 text-white sm:p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-[9px] font-bold uppercase tracking-wider text-cyan-300">Current position</p><b className="mt-1 block text-sm">{milestones[shipmentPoint][0]}</b></div><Plane className="h-6 w-6 text-cyan-300" /></div><div className="mt-6 flex gap-3 overflow-x-auto pb-2">{milestones.map(([label,Icon],index) => <button key={label} onClick={() => setShipmentPoint(index)} className="min-w-20 text-center"><span className={`mx-auto flex h-9 w-9 items-center justify-center rounded-full border-2 ${index <= shipmentPoint ? 'border-cyan-300 bg-cyan-300 text-slate-950' : 'border-white/20 bg-slate-900 text-slate-500'}`}><Icon className="h-4 w-4" /></span><span className="mt-2 block text-[8px] text-slate-400">{label}</span></button>)}</div><p className="mt-5 rounded-xl bg-white/[0.06] p-3 text-[10px] leading-relaxed text-slate-300">Goods are currently in transit from Tanjung Priok to Tokyo Port.</p></div><button onClick={() => setShipmentPoint((point) => Math.min(point + 1, milestones.length - 1))} className={`${action} mt-5 w-full bg-blue-600 text-white`}><MapPin className="h-4 w-4" />Track shipment</button></Card>;
  }
  if (active === 'Settlement') {
    return <Card className="p-5 sm:p-6"><Badge tone="green">Final partner process</Badge><h2 className="mt-3 font-heading text-xl font-extrabold">Shipment complete. Final confirmation is in progress.</h2><div className="mt-5 grid gap-3 sm:grid-cols-3"><StatusTile title="Shipment milestones" copy="All completed" icon={CheckCircle2} /><StatusTile title="Buyer confirmation" copy={settlementChecked ? 'Confirmed' : 'Pending'} icon={Users} /><StatusTile title="Partner review" copy="In progress" icon={Landmark} /></div><div className="mt-5 rounded-2xl border border-blue-500/20 bg-blue-500/[0.05] p-5"><div className="flex gap-3"><Clock3 className="h-5 w-5 shrink-0 text-blue-500" /><div><b className="block text-xs">Settlement under partner review</b><p className="mt-2 text-[11px] leading-relaxed text-slate-500 dark:text-slate-300">The buyer and settlement partner are reviewing completed shipment evidence. Estimated completion: within 7 business days.</p></div></div></div><button onClick={() => setSettlementChecked(true)} className={`${action} mt-5 w-full bg-blue-600 text-white`}><FileSearch className="h-4 w-4" />{settlementChecked ? 'Settlement status checked' : 'Check settlement status'}</button></Card>;
  }
  if (active === 'Dealing') return <Card className="p-5 sm:p-6"><Badge>Participants in room</Badge><div className="mt-4 grid gap-3 sm:grid-cols-2">{[['Me — Aruna Export',Send],['Tokyo Natural Foods',Users],['Logistics Partner',Ship],['Settlement Partner',Landmark],['Verifier',ShieldCheck]].map(([label,Icon]) => <div key={label as string} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 text-xs font-bold dark:border-white/10"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-500/10 text-blue-600 dark:text-cyan-300"><Icon className="h-4 w-4" /></span>{label as string}</div>)}</div></Card>;
  if (active === 'Document' || active === 'Verification' || active === 'Review') return <Card className="p-5 sm:p-6"><Badge>Document and verification room</Badge><h2 className="mt-3 font-heading text-xl font-extrabold">I can see exactly what is ready and what needs action.</h2><div className="mt-5 space-y-3">{docs.map(([name,status]) => <button key={name} className="flex min-h-14 w-full items-center gap-3 rounded-xl border border-slate-200 p-3 text-left transition hover:border-blue-500/30 hover:bg-blue-500/[0.04] dark:border-white/10"><FileText className="h-4 w-4 text-blue-500" /><div className="flex-1"><b className="block text-xs">{name}</b><span className="text-[10px] text-slate-400">Shared with buyer and verifier</span></div><Badge tone={status.includes('Needs') ? 'amber' : 'green'}>{status}</Badge></button>)}</div><button className="mt-5 flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-dashed border-blue-500/40 text-xs font-bold text-blue-600 dark:text-cyan-300"><Upload className="h-4 w-4" />Upload evidence</button></Card>;
  if (active === 'Escrow Readiness' || active === 'Proof') return <Card className="p-5 sm:p-6"><Badge tone="amber">Protection and evidence</Badge><h2 className="mt-3 font-heading text-xl font-extrabold">I am preparing the case for regulated partner review.</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{[['Funds readiness','Confirmed by buyer signal',Banknote],['Payment protection layer','Partner review pending',ShieldCheck],['Inspection proof','Uploaded',FileCheck2],['Dispatch proof','Awaiting shipment',PackageCheck]].map(([title,copy,Icon]) => <button key={title as string} className="rounded-xl border border-slate-200 p-4 text-left transition hover:border-blue-500/30 dark:border-white/10"><Icon className="h-5 w-5 text-blue-500" /><b className="mt-3 block text-xs">{title as string}</b><span className="mt-1 block text-[10px] text-slate-400">{copy as string}</span></button>)}</div><div className="mt-5 rounded-xl bg-blue-500/[0.07] p-4"><div className="flex items-center justify-between"><div><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Escrow readiness</p><b className="mt-1 block font-heading text-3xl text-blue-600 dark:text-cyan-300">82%</b></div><ShieldCheck className="h-8 w-8 text-blue-500" /></div></div><p className="mt-4 rounded-xl bg-amber-500/[0.08] p-4 text-[11px] leading-relaxed text-slate-500 dark:text-slate-300">NEXIIport visualizes readiness and evidence. Financial settlement remains subject to regulated partner review.</p></Card>;
  return <Card className="p-5 sm:p-6"><Badge tone="green">Shipment and settlement journey</Badge><h2 className="mt-3 font-heading text-xl font-extrabold">I can follow where my goods are and what comes next.</h2><div className="mt-6 overflow-hidden rounded-2xl bg-slate-950 p-4 text-white sm:p-5"><div className="flex items-center justify-between"><div><p className="text-[9px] font-bold uppercase tracking-wider text-cyan-300">Live shipment POV</p><b className="mt-1 block text-sm">Goods are currently in transit</b></div><Plane className="h-5 w-5 text-cyan-300" /></div><div className="relative mt-7"><div className="absolute left-4 right-4 top-4 h-0.5 bg-white/10" /><div className="absolute left-4 top-4 h-0.5 w-[42%] bg-gradient-to-r from-blue-500 to-cyan-300" /><div className="relative grid grid-cols-6 gap-1">{[['Warehouse',Warehouse],['Port',Ship],['In transit',Plane],['Customs',ShieldCheck],['Destination',MapPin],['Received',CheckCircle2]].map(([label,Icon],index) => <div key={label as string} className="min-w-0 text-center"><span className={`mx-auto flex h-8 w-8 items-center justify-center rounded-full border-2 ${index < 3 ? 'border-cyan-300 bg-cyan-400 text-slate-950' : 'border-white/20 bg-slate-900 text-slate-500'}`}><Icon className="h-3.5 w-3.5" /></span><span className="mt-2 hidden text-[8px] text-slate-400 sm:block">{label as string}</span></div>)}</div></div><p className="mt-6 rounded-xl bg-white/[0.06] p-3 text-[10px] text-slate-300">Kulon Progo → Tanjung Priok → Tokyo Port → Buyer warehouse</p></div><div className="mt-5 rounded-xl bg-emerald-500/[0.07] p-4"><div className="flex gap-3"><Clock3 className="h-4 w-4 text-emerald-500" /><div><b className="block text-xs">Settlement readiness: ready for partner review</b><p className="mt-1 text-[10px] text-slate-400">Verified documents, buyer confirmation, and shipment evidence support the recommendation.</p></div></div></div></Card>;
}

function ExportAIPanel({ active, guide, step, setStep }: { active: string; guide: typeof stageGuidance[number]; step: number; setStep: (step: number) => void }) {
  return <Card className="p-5"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-gradient-to-br from-blue-600 to-cyan-400 text-white shadow-lg shadow-blue-500/20"><Bot className="h-5 w-5" /></span><div><p className="text-[9px] font-bold uppercase tracking-wider text-blue-600 dark:text-cyan-300">NEXII AI guidance</p><b className="text-xs">{active} support</b></div></div><div className="mt-4 rounded-xl bg-blue-500/[0.07] p-4"><p className="text-[9px] font-bold uppercase tracking-wider text-blue-600 dark:text-cyan-300">AI suggestion</p><p className="mt-2 text-xs leading-relaxed">{guide.ai}</p></div><button onClick={() => setStep(Math.min(step + 1, exportSteps.length - 1))} disabled={step === exportSteps.length - 1} className="mt-4 flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-slate-950 text-xs font-bold text-white disabled:opacity-40 dark:bg-cyan-300 dark:text-slate-950">Go to next stage <ArrowRight className="h-4 w-4" /></button><p className="mt-3 text-[9px] leading-relaxed text-slate-400">Prototype guidance only. Financial actions remain with regulated partners.</p></Card>;
}

function StatusTile({ title, copy, icon: Icon }: { title: string; copy: string; icon: IconType }) {
  return <div className="rounded-xl bg-slate-50 p-4 dark:bg-white/[0.04]"><Icon className="h-5 w-5 text-blue-500" /><b className="mt-3 block text-xs">{title}</b><span className="mt-1 block text-[10px] text-slate-400">{copy}</span></div>;
}

function RevenueCard() {
  return <Card className="p-5"><div className="flex items-start justify-between"><div><p className="text-[9px] font-bold uppercase tracking-wider text-emerald-600 dark:text-emerald-300">Estimated revenue</p><b className="mt-2 block font-heading text-2xl">USD 18,600</b></div><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-500/10 text-emerald-500"><TrendingUp className="h-5 w-5" /></span></div><div className="mt-4 grid grid-cols-2 gap-3 text-[10px]"><div><span className="text-slate-400">Product</span><b className="mt-1 block">Coconut Sugar</b></div><div><span className="text-slate-400">Volume</span><b className="mt-1 block">2 tons</b></div><div><span className="text-slate-400">Destination</span><b className="mt-1 block">Japan</b></div><div><span className="text-slate-400">Estimated margin</span><b className="mt-1 block text-emerald-500">+18% projected</b></div></div><p className="mt-4 border-t border-slate-200 pt-3 text-[9px] leading-relaxed text-slate-400 dark:border-white/10">Based on current export case and expected settlement.</p></Card>;
}

function SupportCard() {
  const [contacted, setContacted] = useState(false);
  return <Card className="p-5"><div className="flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-500/10 text-blue-600 dark:text-cyan-300"><Headphones className="h-5 w-5" /></span><div><b className="block text-xs">Customer Support</b><p className="mt-1 text-[10px] leading-relaxed text-slate-400">Need help with export flow or documents?</p></div></div><button onClick={() => setContacted(true)} className="mt-4 flex min-h-10 w-full items-center justify-center gap-2 rounded-xl border border-blue-500/30 text-[10px] font-bold text-blue-600 dark:text-cyan-300"><MessageCircle className="h-3.5 w-3.5" />{contacted ? 'Support request sent' : 'Chat support'}</button><p className="mt-3 text-center text-[9px] text-slate-400">Response within 1 business day</p></Card>;
}
